apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: microservices
spec:
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app-name: order