apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: payment
  template:
    metadata:
      labels:
        app-name: payment
    spec:
      containers:
        - name: payment
          image: "qanguyen/microservices-payment:latest"
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
