apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: microservices
spec:
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app-name: payment