apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: microservices
spec:
  ports:
    - name: backend
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app-name: delivery